name: CI Workflow
on:
  push:
    branches:
    - master

jobs:
  cross-compile-windows:
    runs-on: ubuntu-latest
    name: Cross Compile Windows
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build Pause and Wincat
      run: |
        cd build/pause
        make build OS=windows
    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-pause-container-binaries
        path: |
          build/pause/bin

  build-containers:
    runs-on: windows-2019
    name: Build Containers
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download a single artifact
      uses: actions/download-artifact@v4
      with:
        name: windows-pause-container-binaries
    - name: Docker Build
      run: |
        docker build -f build/pause/Dockerfile_windows --build-arg BASE=mcr.microsoft.com/windows/nanoserver:ltsc2019 --build-arg ARCH=amd64 build/pause
