name: CI Workflow
on:
  push:
    branches:
    - master

jobs:
  cross-compile-windows:
    runs-on: ubuntu-latest
    name: Cross Compile Windows
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build Pause and Wincat
      run: |
        cd build/pause
        make build OS=windows

  build-containers:
    runs-on: windows-2019
    name: Build Containers
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Msys2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          make
          git
    - name: Build Pre-reqs
      shell: msys2 {0}
      run: |
        export OS=windows
        export ALL_OSVERSIONS=ltsc2019
        export OSVERSION=ltsc2019
        cd build/pause
        make build
    - name: Docker Build
      run: |
        docker build -f build/pause/Dockerfile_windows --build-arg BASE=mcr.microsoft.com/windows/nanoserver:ltsc2019 --build-arg ARCH=amd64 build/pause
